// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbABrlJwRTvWYEoGDyw3wmxyfL2YJE73E',
    appId: '1:604543360938:web:9b8886852fad9c5d6115d3',
    messagingSenderId: '604543360938',
    projectId: 'bot-final-eb1ac',
    authDomain: 'bot-final-eb1ac.firebaseapp.com',
    storageBucket: 'bot-final-eb1ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiu8LsrCxmRUUMcrg_0Mbwu8cVmsSGDxU',
    appId: '1:604543360938:android:d0e25d35f4f1f7806115d3',
    messagingSenderId: '604543360938',
    projectId: 'bot-final-eb1ac',
    storageBucket: 'bot-final-eb1ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWg_ETyNkOkD9qfac_1NLrwGJW4dr4FH4',
    appId: '1:604543360938:ios:1e6d5afe2b6dbec06115d3',
    messagingSenderId: '604543360938',
    projectId: 'bot-final-eb1ac',
    storageBucket: 'bot-final-eb1ac.appspot.com',
    iosClientId: '604543360938-863916upd748u7kif9v1ic9dm12d7u78.apps.googleusercontent.com',
    iosBundleId: 'com.example.botFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWg_ETyNkOkD9qfac_1NLrwGJW4dr4FH4',
    appId: '1:604543360938:ios:1e6d5afe2b6dbec06115d3',
    messagingSenderId: '604543360938',
    projectId: 'bot-final-eb1ac',
    storageBucket: 'bot-final-eb1ac.appspot.com',
    iosClientId: '604543360938-863916upd748u7kif9v1ic9dm12d7u78.apps.googleusercontent.com',
    iosBundleId: 'com.example.botFinal',
  );
}
